-- ========================================
-- SCHEMA PARA SISTEMA DE LOGÍSTICA
-- Base de datos: H2
-- ========================================

-- Tabla: PROVINCIAS
CREATE TABLE PROVINCIAS (
    ID_PROVINCIA IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_PROVINCIAS_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: CIUDADES
CREATE TABLE CIUDADES (
    ID_CIUDAD IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    ID_PROVINCIA BIGINT NOT NULL,
    CONSTRAINT FK_CIUDADES_PROVINCIA FOREIGN KEY (ID_PROVINCIA)
        REFERENCES PROVINCIAS(ID_PROVINCIA)
);

-- Tabla: TIPOS_DOCUMENTOS
CREATE TABLE TIPOS_DOCUMENTOS (
    ID_TIPO_DOCUMENTO IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_TIPOS_DOCUMENTOS_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: TIPOS_TRAMOS (Categorías de tramos)
CREATE TABLE TIPOS_TRAMOS (
    ID_TIPO_TRAMO IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    DESCRIPCION VARCHAR(200),
    CONSTRAINT UQ_TIPOS_TRAMOS_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: ESTADOS_TRAMOS
CREATE TABLE ESTADOS_TRAMOS (
    ID_ESTADO_TRAMO IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_ESTADOS_TRAMOS_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: ESTADOS_CONTENEDORES
CREATE TABLE ESTADOS_CONTENEDORES (
    ID_ESTADO_CONTENEDOR IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_ESTADOS_CONTENEDORES_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: ESTADOS_SOLICITUDES
CREATE TABLE ESTADOS_SOLICITUDES (
    ID_ESTADO_SOLICITUD IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_ESTADOS_SOLICITUDES_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: CLIENTES
CREATE TABLE CLIENTES (
    ID_CLIENTE IDENTITY PRIMARY KEY,
    NRO_DOCUMENTO VARCHAR(20) NOT NULL,
    ID_TIPO_DOCUMENTO BIGINT NOT NULL,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    TELEFONO VARCHAR(50),
    EMAIL VARCHAR(50),
    DIRECCION VARCHAR(200),
    CONSTRAINT UQ_CLIENTES_DOCUMENTO UNIQUE (NRO_DOCUMENTO, ID_TIPO_DOCUMENTO),
    CONSTRAINT FK_CLIENTES_TIPO_DOC FOREIGN KEY (ID_TIPO_DOCUMENTO)
        REFERENCES TIPOS_DOCUMENTOS(ID_TIPO_DOCUMENTO)
);

-- Tabla: TRANSPORTISTAS
CREATE TABLE TRANSPORTISTAS (
    ID_TRANSPORTISTA IDENTITY PRIMARY KEY,
    NRO_DOCUMENTO VARCHAR(20) NOT NULL,
    ID_TIPO_DOCUMENTO BIGINT NOT NULL,
    NOMBRE VARCHAR(80) NOT NULL,
    APELLIDO VARCHAR(80) NOT NULL,
    TELEFONO VARCHAR(50),
    EMAIL VARCHAR(50),
    DIRECCION VARCHAR(200),
    CONSTRAINT UQ_TRANSPORTISTAS_DOCUMENTO UNIQUE (NRO_DOCUMENTO, ID_TIPO_DOCUMENTO),
    CONSTRAINT FK_TRANSPORTISTAS_TIPO_DOC FOREIGN KEY (ID_TIPO_DOCUMENTO)
        REFERENCES TIPOS_DOCUMENTOS(ID_TIPO_DOCUMENTO)
);

-- Tabla: CAMIONES
CREATE TABLE CAMIONES (
    PATENTE VARCHAR(20) PRIMARY KEY,
    CAPACIDAD_PESO DECIMAL(10, 2),
    CAPACIDAD_VOLUMEN DECIMAL(10, 2),
    CONSUMO DECIMAL(10, 2),
    CONSUMO_PROMEDIO DECIMAL(10, 2),
    ESTA_DISPONIBLE BOOLEAN,
    COSTO_X_KILOMETRO DECIMAL(10, 2),
    NRO_DOCUMENTO_TRANSPORTISTA VARCHAR(20) NOT NULL,
    ID_TIPO_DOCUMENTO_TRANSPORTISTA BIGINT NOT NULL,
    CONSTRAINT FK_CAMIONES_TRANSPORTISTA FOREIGN KEY (NRO_DOCUMENTO_TRANSPORTISTA, ID_TIPO_DOCUMENTO_TRANSPORTISTA)
        REFERENCES TRANSPORTISTAS(NRO_DOCUMENTO, ID_TIPO_DOCUMENTO)
);

-- Tabla: DEPOSITOS
CREATE TABLE DEPOSITOS (
    ID_DEPOSITO IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    DIRECCION VARCHAR(200),
    LATITUD DECIMAL(11, 8) NOT NULL,
    LONGITUD DECIMAL(11, 8) NOT NULL,
    ID_CIUDAD BIGINT NOT NULL,
    CONSTRAINT FK_DEPOSITOS_CIUDAD FOREIGN KEY (ID_CIUDAD)
        REFERENCES CIUDADES(ID_CIUDAD)
);

-- Tabla: CONTENEDORES
CREATE TABLE CONTENEDORES (
    ID_CONTENEDOR IDENTITY PRIMARY KEY,
    PESO DECIMAL(10, 2),
    VOLUMEN DECIMAL(10, 2),
    LATITUD DECIMAL(11, 8) NOT NULL,
    LONGITUD DECIMAL(11, 8) NOT NULL,
    COSTO_X_PESO_X_VOLUMEN DECIMAL(10, 2),
    ID_ESTADO_CONTENEDOR BIGINT NOT NULL,
    CONSTRAINT FK_CONTENEDORES_ESTADO FOREIGN KEY (ID_ESTADO_CONTENEDOR)
        REFERENCES ESTADOS_CONTENEDORES(ID_ESTADO_CONTENEDOR)
);

-- Tabla: SOLICITUDES
CREATE TABLE SOLICITUDES (
    NRO_SOLICITUD IDENTITY PRIMARY KEY,
    DIRECCION_ORIGEN VARCHAR(200),
    DIRECCION_DESTINO VARCHAR(200),
    ID_CIUDAD_ORIGEN BIGINT NOT NULL,
    ID_CIUDAD_DESTINO BIGINT NOT NULL,
    LATITUD_ORIGEN DECIMAL(11, 8) NOT NULL,
    LONGITUD_ORIGEN DECIMAL(11, 8) NOT NULL,
    LATITUD_DESTINO DECIMAL(11, 8) NOT NULL,
    LONGITUD_DESTINO DECIMAL(11, 8) NOT NULL,
    FECHA_INICIO_SOLICITUD DATE NOT NULL,
    FECHA_FIN_SOLICITUD DATE,
    COSTO_ESTIMADO DECIMAL(10, 2),
    COSTO_REAL DECIMAL(10, 2),
    TIEMPO_ESTIMADO INT,
    TIEMPO_REAL INT,
    ID_ESTADO_SOLICITUD BIGINT NOT NULL,
    ID_CONTENEDOR BIGINT NOT NULL,
    NRO_DOCUMENTO_CLIENTE VARCHAR(20) NOT NULL,
    ID_TIPO_DOCUMENTO_CLIENTE BIGINT NOT NULL,
    CONSTRAINT FK_SOLICITUDES_CIUDAD_ORIGEN FOREIGN KEY (ID_CIUDAD_ORIGEN)
        REFERENCES CIUDADES(ID_CIUDAD),
    CONSTRAINT FK_SOLICITUDES_CIUDAD_DESTINO FOREIGN KEY (ID_CIUDAD_DESTINO)
        REFERENCES CIUDADES(ID_CIUDAD),
    CONSTRAINT FK_SOLICITUDES_ESTADO FOREIGN KEY (ID_ESTADO_SOLICITUD)
        REFERENCES ESTADOS_SOLICITUDES(ID_ESTADO_SOLICITUD),
    CONSTRAINT FK_SOLICITUDES_CONTENEDOR FOREIGN KEY (ID_CONTENEDOR)
        REFERENCES CONTENEDORES(ID_CONTENEDOR),
    CONSTRAINT FK_SOLICITUDES_CLIENTE FOREIGN KEY (NRO_DOCUMENTO_CLIENTE, ID_TIPO_DOCUMENTO_CLIENTE)
        REFERENCES CLIENTES(NRO_DOCUMENTO, ID_TIPO_DOCUMENTO)
);

-- Tabla: RUTAS
CREATE TABLE RUTAS (
    ID_RUTA IDENTITY PRIMARY KEY,
    CANTIDAD_TRAMOS INT,
    CANTIDAD_ESTADIAS INT,
    NRO_SOLICITUD BIGINT NOT NULL,
    CONSTRAINT FK_RUTAS_SOLICITUD FOREIGN KEY (NRO_SOLICITUD)
        REFERENCES SOLICITUDES(NRO_SOLICITUD)
);

-- Tabla: ESTADIAS (relación entre CONTENEDORES y DEPOSITOS)
CREATE TABLE ESTADIAS (
    ID_ESTADIA IDENTITY PRIMARY KEY
    FECHA_HORA_INICIO_ESTIMADA TIMESTAMP,
    FECHA_HORA_FIN_ESTIMADA TIMESTAMP,
    FECHA_HORA_INICIO_REAL TIMESTAMP,
    FECHA_HORA_FIN_REAL TIMESTAMP,
    COSTO_ESTIMADO DECIMAL(10, 2),
    COSTO_REAL DECIMAL(10, 2),
    ID_DEPOSITO BIGINT NOT NULL,
    ID_CONTENEDOR BIGINT NOT NULL,
    ID_RUTA BIGINT NOT NULL,
    CONSTRAINT FK_ESTADIAS_DEPOSITO FOREIGN KEY (ID_DEPOSITO)
        REFERENCES DEPOSITOS(ID_DEPOSITO),
    CONSTRAINT FK_ESTADIAS_CONTENEDOR FOREIGN KEY (ID_CONTENEDOR)
        REFERENCES CONTENEDORES(ID_CONTENEDOR),
    CONSTRAINT FK_ESTADIAS_RUTA FOREIGN KEY (ID_RUTA)
        REFERENCES RUTAS(ID_RUTA)
);

-- Tabla: TRAMOS
CREATE TABLE TRAMOS (
    ID_TRAMO IDENTITY PRIMARY KEY,
    LATITUD_ORIGEN DECIMAL(11, 8) NOT NULL,
    LONGITUD_ORIGEN DECIMAL(11, 8) NOT NULL,
    LATITUD_DESTINO DECIMAL(11, 8) NOT NULL,
    LONGITUD_DESTINO DECIMAL(11, 8) NOT NULL,
    FECHA_HORA_INICIO_ESTIMADA TIMESTAMP,
    FECHA_HORA_FIN_ESTIMADA TIMESTAMP,
    FECHA_HORA_INICIO_REAL TIMESTAMP,
    FECHA_HORA_FIN_REAL TIMESTAMP,
    COSTO_ESTIMADO DECIMAL(10, 2),
    COSTO_REAL DECIMAL(10, 2),
    ID_RUTA BIGINT NOT NULL,
    ID_TIPO_TRAMO BIGINT,
    ID_ESTADO_TRAMO BIGINT NOT NULL,
    PATENTE VARCHAR(20) NOT NULL,
    ID_DEPOSITO_ORIGEN BIGINT NOT NULL,
    ID_DEPOSITO_DESTINO BIGINT NOT NULL,
    CONSTRAINT FK_TRAMOS_RUTA FOREIGN KEY (ID_RUTA)
        REFERENCES RUTAS(ID_RUTA),
    CONSTRAINT FK_TRAMOS_TIPO FOREIGN KEY (ID_TIPO_TRAMO)
        REFERENCES TIPOS_TRAMOS(ID_TIPO_TRAMO),
    CONSTRAINT FK_TRAMOS_ESTADO FOREIGN KEY (ID_ESTADO_TRAMO)
        REFERENCES ESTADOS_TRAMOS(ID_ESTADO_TRAMO),
    CONSTRAINT FK_TRAMOS_CAMION FOREIGN KEY (PATENTE)
        REFERENCES CAMIONES(PATENTE),
    CONSTRAINT FK_TRAMOS_DEPOSITO_ORIGEN FOREIGN KEY (ID_DEPOSITO_ORIGEN)
        REFERENCES DEPOSITOS(ID_DEPOSITO),
    CONSTRAINT FK_TRAMOS_DEPOSITO_DESTINO FOREIGN KEY (ID_DEPOSITO_DESTINO)
        REFERENCES DEPOSITOS(ID_DEPOSITO)
);

-- ========================================
-- TABLAS AUXILIARES
-- ========================================

-- Tabla: TARIFAS
CREATE TABLE TARIFAS (
    ID_TARIFA IDENTITY PRIMARY KEY,
    CONCEPTO VARCHAR(50),
    COSTO DECIMAL(10, 2) NOT NULL,
    FECHA_HORA_INICIO TIMESTAMP NOT NULL,
    FECHA_HORA_FIN TIMESTAMP NOT NULL
);

-- ========================================
-- ÍNDICES PARA MEJORAR RENDIMIENTO
-- ========================================

-- Índices en Foreign Keys
CREATE INDEX IX_CIUDADES_PROVINCIA ON CIUDADES(ID_PROVINCIA);
CREATE INDEX IX_DEPOSITOS_CIUDAD ON DEPOSITOS(ID_CIUDAD);
CREATE INDEX IX_TRAMOS_RUTA ON TRAMOS(ID_RUTA);
CREATE INDEX IX_TRAMOS_ESTADO ON TRAMOS(ID_ESTADO_TRAMO);
CREATE INDEX IX_SOLICITUDES_CIUDAD_ORIGEN ON SOLICITUDES(ID_CIUDAD_ORIGEN);
CREATE INDEX IX_SOLICITUDES_CIUDAD_DESTINO ON SOLICITUDES(ID_CIUDAD_DESTINO);
-- ========================================
-- SCHEMA PARA SISTEMA DE LOGÍSTICA
-- Base de datos: H2
-- ========================================

-- ========================================
-- TABLAS DE SOPORTE
-- ========================================

-- Tabla: PROVINCIAS
CREATE TABLE PROVINCIAS (
    ID_PROVINCIA IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_PROVINCIAS_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: CIUDADES
CREATE TABLE CIUDADES (
    ID_CIUDAD IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    ID_PROVINCIA BIGINT NOT NULL,
    CONSTRAINT FK_CIUDADES_PROVINCIA FOREIGN KEY (ID_PROVINCIA)
        REFERENCES PROVINCIAS(ID_PROVINCIA)
);

-- Tabla: TIPOS_DOCUMENTOS
CREATE TABLE TIPOS_DOCUMENTOS (
    ID_TIPO_DOCUMENTO IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_TIPOS_DOCUMENTOS_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: TIPOS_TRAMOS (Categorías de tramos)
CREATE TABLE TIPOS_TRAMOS (
    ID_TIPO_TRAMO IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    DESCRIPCION VARCHAR(200),
    CONSTRAINT UQ_TIPOS_TRAMOS_NOMBRE UNIQUE (NOMBRE)
);

-- ========================================
-- TABLAS DE ESTADOS
-- ========================================

-- Tabla: ESTADOS_TRAMOS
CREATE TABLE ESTADOS_TRAMOS (
    ID_ESTADO_TRAMO IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_ESTADOS_TRAMOS_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: ESTADOS_CONTENEDORES
CREATE TABLE ESTADOS_CONTENEDORES (
    ID_ESTADO_CONTENEDOR IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_ESTADOS_CONTENEDORES_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: ESTADOS_SOLICITUDES
CREATE TABLE ESTADOS_SOLICITUDES (
    ID_ESTADO_SOLICITUD IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_ESTADOS_SOLICITUDES_NOMBRE UNIQUE (NOMBRE)
);

-- ========================================
-- TABLAS PRINCIPALES
-- ========================================

-- Tabla: CLIENTES
CREATE TABLE CLIENTES (
    ID_CLIENTE IDENTITY PRIMARY KEY,
    NRO_DOCUMENTO VARCHAR(20) NOT NULL,
    ID_TIPO_DOCUMENTO BIGINT NOT NULL,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    TELEFONO VARCHAR(50),
    EMAIL VARCHAR(50),
    DIRECCION VARCHAR(200),
    CONSTRAINT UQ_CLIENTES_DOCUMENTO UNIQUE (NRO_DOCUMENTO, ID_TIPO_DOCUMENTO),
    CONSTRAINT FK_CLIENTES_TIPO_DOC FOREIGN KEY (ID_TIPO_DOCUMENTO)
        REFERENCES TIPOS_DOCUMENTOS(ID_TIPO_DOCUMENTO)
);

-- Tabla: CONTENEDORES
CREATE TABLE CONTENEDORES (
    ID_CONTENEDOR IDENTITY PRIMARY KEY,
    PESO DECIMAL(10, 2),
    VOLUMEN DECIMAL(10, 2),
    LATITUD DECIMAL(11, 8) NOT NULL,
    LONGITUD DECIMAL(11, 8) NOT NULL,
    COSTO_X_PESO_X_VOLUMEN DECIMAL(10, 2),
    NRO_SOLICITUD BIGINT NOT NULL,
    ID_ESTADO_CONTENEDOR BIGINT NOT NULL,
    CONSTRAINT FK_CONTENEDORES_SOLICITUD FOREIGN KEY (NRO_SOLICITUD)
        REFERENCES SOLICITUDES(ID_SOLICITUD),
    CONSTRAINT FK_CONTENEDORES_ESTADO FOREIGN KEY (ID_ESTADO_CONTENEDOR)
        REFERENCES ESTADOS_CONTENEDORES(ID_ESTADO_CONTENEDOR)
);

-- Tabla: DEPOSITOS
CREATE TABLE DEPOSITOS (
    ID_DEPOSITO IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    DIRECCION VARCHAR(200),
    LATITUD DECIMAL(11, 8) NOT NULL,
    LONGITUD DECIMAL(11, 8) NOT NULL,
    ID_CIUDAD BIGINT NOT NULL,
    CONSTRAINT FK_DEPOSITOS_CIUDAD FOREIGN KEY (ID_CIUDAD)
        REFERENCES CIUDADES(ID_CIUDAD)
);

-- Tabla: ESTADIAS (relación entre CONTENEDORES y DEPOSITOS)
CREATE TABLE ESTADIAS (
    ID_DEPOSITO BIGINT NOT NULL,
    ID_CONTENEDOR BIGINT NOT NULL,
    FECHA_HORA_INICIO_ESTIMADA TIMESTAMP,
    FECHA_HORA_FIN_ESTIMADA TIMESTAMP,
    FECHA_HORA_INICIO_REAL TIMESTAMP,
    FECHA_HORA_FIN_REAL TIMESTAMP,
    COSTO_ESTIMADO DECIMAL(10, 2),
    COSTO_REAL DECIMAL(10, 2),
    ID_RUTA BIGINT NOT NULL,
    PRIMARY KEY (ID_DEPOSITO, ID_CONTENEDOR),
    CONSTRAINT FK_ESTADIAS_DEPOSITO FOREIGN KEY (ID_DEPOSITO)
        REFERENCES DEPOSITOS(ID_DEPOSITO),
    CONSTRAINT FK_ESTADIAS_CONTENEDOR FOREIGN KEY (ID_CONTENEDOR)
        REFERENCES CONTENEDORES(ID_CONTENEDOR),
    CONSTRAINT FK_ESTADIAS_RUTA FOREIGN KEY (ID_RUTA)
        REFERENCES RUTAS(ID_RUTA)
);

-- Tabla: SOLICITUDES
CREATE TABLE SOLICITUDES (
    NRO_SOLICITUD IDENTITY PRIMARY KEY,
    DIRECCION_ORIGEN VARCHAR(200),
    DIRECCION_DESTINO VARCHAR(200),
    ID_CIUDAD_ORIGEN BIGINT NOT NULL,
    ID_CIUDAD_DESTINO BIGINT NOT NULL,
    LATITUD_ORIGEN DECIMAL(11, 8) NOT NULL,
    LONGITUD_ORIGEN DECIMAL(11, 8) NOT NULL,
    LATITUD_DESTINO DECIMAL(11, 8) NOT NULL,
    LONGITUD_DESTINO DECIMAL(11, 8) NOT NULL,
    FECHA_INICIO_SOLICITUD DATE NOT NULL,
    FECHA_FIN_SOLICITUD DATE,
    COSTO_ESTIMADO DECIMAL(10, 2),
    COSTO_REAL DECIMAL(10, 2),
    TIEMPO_ESTIMADO INT,
    TIEMPO_REAL INT,
    ID_ESTADO_SOLICITUD BIGINT NOT NULL,
    ID_CONTENEDOR BIGINT NOT NULL,
    NRO_DOCUMENTO_CLIENTE VARCHAR(20) NOT NULL,
    ID_TIPO_DOCUMENTO_CLIENTE BIGINT NOT NULL,
    CONSTRAINT FK_SOLICITUDES_CIUDAD_ORIGEN FOREIGN KEY (ID_CIUDAD_ORIGEN)
        REFERENCES CIUDADES(ID_CIUDAD),
    CONSTRAINT FK_SOLICITUDES_CIUDAD_DESTINO FOREIGN KEY (ID_CIUDAD_DESTINO)
        REFERENCES CIUDADES(ID_CIUDAD),
    CONSTRAINT FK_SOLICITUDES_ESTADO FOREIGN KEY (ID_ESTADO_SOLICITUD)
        REFERENCES ESTADOS_SOLICITUDES(ID_ESTADO_SOLICITUD),
    CONSTRAINT FK_SOLICITUDES_CONTENEDOR FOREIGN KEY (ID_CONTENEDOR)
        REFERENCES CONTENEDORES(ID_CONTENEDOR),
    CONSTRAINT FK_SOLICITUDES_CLIENTE FOREIGN KEY (NRO_DOCUMENTO_CLIENTE, ID_TIPO_DOCUMENTO_CLIENTE)
        REFERENCES CLIENTES(NRO_DOCUMENTO, ID_TIPO_DOCUMENTO)
);

-- ========================================
-- TABLAS DE RUTAS
-- ========================================

-- Tabla: TRANSPORTISTAS
CREATE TABLE TRANSPORTISTAS (
    ID_TRANSPORTISTA IDENTITY PRIMARY KEY,
    NRO_DOCUMENTO VARCHAR(20) NOT NULL,
    ID_TIPO_DOCUMENTO BIGINT NOT NULL,
    NOMBRE VARCHAR(80) NOT NULL,
    APELLIDO VARCHAR(80) NOT NULL,
    TELEFONO VARCHAR(50),
    EMAIL VARCHAR(50),
    DIRECCION VARCHAR(200),
    CONSTRAINT UQ_TRANSPORTISTAS_DOCUMENTO UNIQUE (NRO_DOCUMENTO, ID_TIPO_DOCUMENTO),
    CONSTRAINT FK_TRANSPORTISTAS_TIPO_DOC FOREIGN KEY (ID_TIPO_DOCUMENTO)
        REFERENCES TIPOS_DOCUMENTOS(ID_TIPO_DOCUMENTO)
);

-- Tabla: CAMIONES
CREATE TABLE CAMIONES (
    PATENTE VARCHAR(20) PRIMARY KEY,
    CAPACIDAD_PESO DECIMAL(10, 2),
    CAPACIDAD_VOLUMEN DECIMAL(10, 2),
    CONSUMO DECIMAL(10, 2),
    CONSUMO_PROMEDIO DECIMAL(10, 2),
    ESTA_DISPONIBLE BOOLEAN,
    COSTO_X_KILOMETRO DECIMAL(10, 2),
    NRO_DOCUMENTO_TRANSPORTISTA VARCHAR(20) NOT NULL,
    ID_TIPO_DOCUMENTO_TRANSPORTISTA BIGINT NOT NULL,
    CONSTRAINT FK_CAMIONES_TRANSPORTISTA FOREIGN KEY (NRO_DOCUMENTO_TRANSPORTISTA, ID_TIPO_DOCUMENTO_TRANSPORTISTA)
        REFERENCES TRANSPORTISTAS(NRO_DOCUMENTO, ID_TIPO_DOCUMENTO)
);

-- Tabla: RUTAS
CREATE TABLE RUTAS (
    ID_RUTA IDENTITY PRIMARY KEY,
    CANTIDAD_TRAMOS INT,
    CANTIDAD_ESTADIAS INT,
    NRO_SOLICITUD BIGINT NOT NULL,
    CONSTRAINT FK_RUTAS_SOLICITUD FOREIGN KEY (NRO_SOLICITUD)
        REFERENCES SOLICITUDES(ID_SOLICITUD)
);

-- Tabla: TRAMOS
CREATE TABLE TRAMOS (
    ID_TRAMO IDENTITY PRIMARY KEY,
    LATITUD_ORIGEN DECIMAL(11, 8) NOT NULL,
    LONGITUD_ORIGEN DECIMAL(11, 8) NOT NULL,
    LATITUD_DESTINO DECIMAL(11, 8) NOT NULL,
    LONGITUD_DESTINO DECIMAL(11, 8) NOT NULL,
    FECHA_HORA_INICIO_ESTIMADA TIMESTAMP,
    FECHA_HORA_FIN_ESTIMADA TIMESTAMP,
    FECHA_HORA_INICIO_REAL TIMESTAMP,
    FECHA_HORA_FIN_REAL TIMESTAMP,
    COSTO_ESTIMADO DECIMAL(10, 2),
    COSTO_REAL DECIMAL(10, 2),
    ID_RUTA BIGINT NOT NULL,
    ID_TIPO_TRAMO BIGINT,
    ID_ESTADO_TRAMO BIGINT NOT NULL,
    PATENTE VARCHAR(20) NOT NULL,
    ID_DEPOSITO_ORIGEN BIGINT NOT NULL,
    ID_DEPOSITO_DESTINO BIGINT NOT NULL,
    CONSTRAINT FK_TRAMOS_RUTA FOREIGN KEY (ID_RUTA)
        REFERENCES RUTAS(ID_RUTA),
    CONSTRAINT FK_TRAMOS_TIPO FOREIGN KEY (ID_TIPO_TRAMO)
        REFERENCES TIPOS_TRAMOS(ID_TIPO_TRAMO),
    CONSTRAINT FK_TRAMOS_ESTADO FOREIGN KEY (ID_ESTADO_TRAMO)
        REFERENCES ESTADOS(ID_ESTADO_TRAMO),
    CONSTRAINT FK_TRAMOS_CAMION FOREIGN KEY (PATENTE)
        REFERENCES CAMIONES(PATENTE),
    CONSTRAINT FK_TRAMOS_DEPOSITO_ORIGEN FOREIGN KEY (ID_DEPOSITO_ORIGEN)
        REFERENCES DEPOSITOS(ID_DEPOSITO),
    CONSTRAINT FK_TRAMOS_DEPOSITO_DESTINO FOREIGN KEY (ID_DEPOSITO_DESTINO)
        REFERENCES DEPOSITOS(ID_DEPOSITO)
);

-- ========================================
-- TABLAS AUXILIARES
-- ========================================

-- Tabla: TARIFAS
CREATE TABLE TARIFAS (
    ID_TARIFA IDENTITY PRIMARY KEY,
    CONCEPTO VARCHAR(50)
    COSTO DECIMAL(10, 2) NOT NULL,
    FECHA_HORA_INICIO TIMESTAMP NOT NULL,
    FECHA_HORA_FIN TIMESTAMP NOT NULL
);

-- ========================================
-- ÍNDICES PARA MEJORAR RENDIMIENTO
-- ========================================

-- Índices en Foreign Keys
CREATE INDEX IX_CIUDADES_PROVINCIA ON CIUDADES(ID_PROVINCIA);
CREATE INDEX IX_DEPOSITOS_CIUDAD ON DEPOSITOS(ID_CIUDAD);
CREATE INDEX IX_TRAMOS_RUTA ON TRAMOS(ID_RUTA);
CREATE INDEX IX_TRAMOS_ESTADO ON TRAMOS(ID_ESTADO_TRAMO);
CREATE INDEX IX_SOLICITUDES_CIUDAD_ORIGEN ON SOLICITUDES(ID_CIUDAD_ORIGEN);
CREATE INDEX IX_SOLICITUDES_CIUDAD_DESTINO ON SOLICITUDES(ID_CIUDAD_DESTINO);
CREATE INDEX IX_SOLICITUDES_CLIENTE ON SOLICITUDES(ID_CLIENTE);
CREATE INDEX IX_SOLICITUDES_ESTADO ON SOLICITUDES(ID_ESTADO_SOLICITUD);
CREATE INDEX IX_CONTENEDORES_ESTADO ON CONTENEDORES(ID_ESTADO_CONTENEDOR);
CREATE INDEX IX_ESTADIAS_CONTENEDOR ON ESTADIAS(ID_CONTENEDOR);
CREATE INDEX IX_ESTADIAS_DEPOSITO ON ESTADIAS(ID_DEPOSITO);
CREATE INDEX IX_SOLICITUDES_ESTADO ON SOLICITUDES(ID_ESTADO_SOLICITUD);
CREATE INDEX IX_CONTENEDORES_ESTADO ON CONTENEDORES(ID_ESTADO_CONTENEDOR);
CREATE INDEX IX_ESTADIAS_CONTENEDOR ON ESTADIAS(ID_CONTENEDOR);
CREATE INDEX IX_ESTADIAS_DEPOSITO ON ESTADIAS(ID_DEPOSITO);
