-- ========================================
-- SCHEMA PARA SISTEMA DE LOGÍSTICA
-- Base de datos: H2
-- ========================================

-- ========================================
-- TABLAS DE CATÁLOGOS BASE
-- ========================================

-- Tabla: PROVINCIAS
CREATE TABLE PROVINCIAS (
    ID_PROVINCIA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_PROVINCIAS_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: CIUDADES
CREATE TABLE CIUDADES (
    ID_CIUDAD INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    ID_PROVINCIA INT NOT NULL,
    LATITUD DECIMAL(10, 7) NOT NULL,
    LONGITUD DECIMAL(10, 7) NOT NULL,
    CONSTRAINT FK_CIUDADES_PROVINCIA FOREIGN KEY (ID_PROVINCIA)
        REFERENCES PROVINCIAS(ID_PROVINCIA)
);
-- ========================================
-- TABLAS DE ESTADOS
-- ========================================

-- Tabla: ESTADOS_TRAMOS
CREATE TABLE ESTADOS_TRAMOS (
    ID_ESTADO_TRAMO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_ESTADOS_TRAMOS_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: ESTADOS_CONTENEDORES
CREATE TABLE ESTADOS_CONTENEDORES (
    ID_ESTADO_CONTENEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_ESTADOS_CONTENEDORES_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: ESTADOS_TRASLADOS
CREATE TABLE ESTADOS_TRASLADOS (
    ID_ESTADO_TRASLADO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_ESTADOS_TRASLADOS_NOMBRE UNIQUE (NOMBRE)
);

-- ========================================
-- TABLAS DE TIPOS Y CATÁLOGOS
-- ========================================

-- Tabla: TIPOS_TRAMOS
CREATE TABLE TIPOS_TRAMOS (
    ID_TIPO_TRAMO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    CONSTRAINT UQ_TIPOS_TRAMOS_NOMBRE UNIQUE (NOMBRE)
);

-- Tabla: TARIFAS
CREATE TABLE TARIFAS (
    ID_TARIFA INT AUTO_INCREMENT PRIMARY KEY,
    CONCEPTO VARCHAR(100) NOT NULL,
    COSTO_X_KILOMETRO DECIMAL(12, 2) NOT NULL,
    CONSTRAINT UQ_TARIFAS_CONCEPTO UNIQUE (CONCEPTO)
);

-- ========================================
-- TABLAS DE PERSONAS
-- ========================================

-- Tabla: CLIENTES
CREATE TABLE CLIENTES (
    NRO_DOCUMENTO INT PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    APELLIDO VARCHAR(80),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100),
    DIRECCION VARCHAR(200),
    ID_CIUDAD INT,
    CONSTRAINT FK_CLIENTES_CIUDAD FOREIGN KEY (ID_CIUDAD)
        REFERENCES CIUDADES(ID_CIUDAD)
);

-- Tabla: TRANSPORTISTAS
CREATE TABLE TRANSPORTISTAS (
    LEGAJO INT PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    APELLIDO VARCHAR(80),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100),
    DIRECCION VARCHAR(200),
    ID_CIUDAD INT,
    CONSTRAINT FK_TRANSPORTISTAS_CIUDAD FOREIGN KEY (ID_CIUDAD)
        REFERENCES CIUDADES(ID_CIUDAD)
);

-- ========================================
-- TABLAS DE RECURSOS
-- ========================================

-- Tabla: CAMIONES
CREATE TABLE CAMIONES (
    PATENTE VARCHAR(20) PRIMARY KEY,
    CAPACIDAD_PESO INT NOT NULL,
    CAPACIDAD_VOLUMEN INT NOT NULL,
    CONSUMO_PROMEDIO DECIMAL(12, 2) NOT NULL,
    ESTA_DISPONIBLE CHAR(1) NOT NULL DEFAULT 'S',
    ID_TARIFA INT NOT NULL,
    CONSTRAINT CHK_CAMIONES_DISPONIBLE CHECK (ESTA_DISPONIBLE IN ('S', 'N')),
    CONSTRAINT FK_CAMIONES_TARIFA FOREIGN KEY (ID_TARIFA)
        REFERENCES TARIFAS(ID_TARIFA)
);

-- Tabla: DEPOSITOS
CREATE TABLE DEPOSITOS (
    ID_DEPOSITO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    COSTO_X_DIA DECIMAL(12, 2) NOT NULL,
    LATITUD DECIMAL(10, 7) NOT NULL,
    LONGITUD DECIMAL(10, 7) NOT NULL,
    DIRECCION VARCHAR(200),
    ID_CIUDAD INT NOT NULL,
    CONSTRAINT FK_DEPOSITOS_CIUDAD FOREIGN KEY (ID_CIUDAD)
        REFERENCES CIUDADES(ID_CIUDAD)
);

-- Tabla: CONTENEDORES
CREATE TABLE CONTENEDORES (
    ID_CONTENEDOR INT AUTO_INCREMENT PRIMARY KEY,
    PESO DECIMAL(12, 2) NOT NULL,
    VOLUMEN DECIMAL(12, 2) NOT NULL,
    COSTO_X_PESO_X_VOLUMEN DECIMAL(12, 2) NOT NULL,
    LATITUD DECIMAL(10, 7) NOT NULL,
    LONGITUD DECIMAL(10, 7) NOT NULL,
    ID_ESTADO_CONTENEDOR INT NOT NULL,
    CONSTRAINT FK_CONTENEDORES_ESTADO FOREIGN KEY (ID_ESTADO_CONTENEDOR)
        REFERENCES ESTADOS_CONTENEDORES(ID_ESTADO_CONTENEDOR)
);

-- ========================================
-- TABLAS DE OPERACIONES PRINCIPALES
-- ========================================

-- Tabla: TRASLADOS
CREATE TABLE TRASLADOS (
    ID_TRASLADO INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_INICIO_TRASLADO TIMESTAMP,
    FECHA_FIN_TRASLADO TIMESTAMP,
    COSTO_ESTIMADO DECIMAL(12, 2),
    COSTO_REAL DECIMAL(12, 2),
    TIEMPO_ESTIMADO TIMESTAMP,
    TIEMPO_REAL TIMESTAMP,
    DIRECCION_ORIGEN VARCHAR(200),
    DIRECCION_DESTINO VARCHAR(200),
    ID_CIUDAD_ORIGEN INT NOT NULL,
    ID_CIUDAD_DESTINO INT NOT NULL,
    ID_CONTENEDOR INT NOT NULL,
    NRO_DOCUMENTO_CLIENTE INT NOT NULL,
    CONSTRAINT FK_TRASLADOS_CIUDAD_ORIGEN FOREIGN KEY (ID_CIUDAD_ORIGEN)
        REFERENCES CIUDADES(ID_CIUDAD),
    CONSTRAINT FK_TRASLADOS_CIUDAD_DESTINO FOREIGN KEY (ID_CIUDAD_DESTINO)
        REFERENCES CIUDADES(ID_CIUDAD),
    CONSTRAINT FK_TRASLADOS_CONTENEDOR FOREIGN KEY (ID_CONTENEDOR)
        REFERENCES CONTENEDORES(ID_CONTENEDOR),
    CONSTRAINT FK_TRASLADOS_CLIENTE FOREIGN KEY (NRO_DOCUMENTO_CLIENTE)
        REFERENCES CLIENTES(NRO_DOCUMENTO)
);

-- Tabla: TRAMOS
CREATE TABLE TRAMOS (
    ID_TRAMO INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_HORA_INICIO_ESTIMADA TIMESTAMP,
    FECHA_HORA_FIN_ESTIMADA TIMESTAMP,
    FECHA_HORA_INICIO_REAL TIMESTAMP,
    FECHA_HORA_FIN_REAL TIMESTAMP,
    COSTO_ESTIMADO DECIMAL(12, 2),
    COSTO_REAL DECIMAL(12, 2),
    DIRECCION_ORIGEN VARCHAR(200),
    DIRECCION_DESTINO VARCHAR(200),
    ID_ESTADO_TRAMO INT NOT NULL,
    ID_TIPO_TRAMO INT NOT NULL,
    PATENTE_CAMION VARCHAR(20) NOT NULL,
    LEGAJO_TRANSPORTISTA INT NOT NULL,
    ID_DEPOSITO_ORIGEN INT,
    ID_DEPOSITO_DESTINO INT,
    ID_TRASLADO INT NOT NULL,
    ID_CIUDAD_ORIGEN INT NOT NULL,
    ID_CIUDAD_DESTINO INT NOT NULL,
    CONSTRAINT FK_TRAMOS_ESTADO FOREIGN KEY (ID_ESTADO_TRAMO)
        REFERENCES ESTADOS_TRAMOS(ID_ESTADO_TRAMO),
    CONSTRAINT FK_TRAMOS_TIPO FOREIGN KEY (ID_TIPO_TRAMO)
        REFERENCES TIPOS_TRAMOS(ID_TIPO_TRAMO),
    CONSTRAINT FK_TRAMOS_CAMION FOREIGN KEY (PATENTE_CAMION)
        REFERENCES CAMIONES(PATENTE),
    CONSTRAINT FK_TRAMOS_TRANSPORTISTA FOREIGN KEY (LEGAJO_TRANSPORTISTA)
        REFERENCES TRANSPORTISTAS(LEGAJO),
    CONSTRAINT FK_TRAMOS_DEPOSITO_ORIGEN FOREIGN KEY (ID_DEPOSITO_ORIGEN)
        REFERENCES DEPOSITOS(ID_DEPOSITO),
    CONSTRAINT FK_TRAMOS_DEPOSITO_DESTINO FOREIGN KEY (ID_DEPOSITO_DESTINO)
        REFERENCES DEPOSITOS(ID_DEPOSITO),
    CONSTRAINT FK_TRAMOS_TRASLADO FOREIGN KEY (ID_TRASLADO)
        REFERENCES TRASLADOS(ID_TRASLADO),
    CONSTRAINT FK_TRAMOS_CIUDAD_ORIGEN FOREIGN KEY (ID_CIUDAD_ORIGEN)
        REFERENCES CIUDADES(ID_CIUDAD),
    CONSTRAINT FK_TRAMOS_CIUDAD_DESTINO FOREIGN KEY (ID_CIUDAD_DESTINO)
        REFERENCES CIUDADES(ID_CIUDAD)
);

-- Tabla: ESTADIAS
CREATE TABLE ESTADIAS (
    ID_ESTADIA INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_HORA_INICIO_ESTIMADA TIMESTAMP,
    FECHA_HORA_FIN_ESTIMADA TIMESTAMP,
    FECHA_HORA_INICIO_REAL TIMESTAMP,
    FECHA_HORA_FIN_REAL TIMESTAMP,
    COSTO_ESTIMADO DECIMAL(12, 2),
    COSTO_REAL DECIMAL(12, 2),
    ID_DEPOSITO INT NOT NULL,
    ID_CONTENEDOR INT NOT NULL,
    ID_TRASLADO INT NOT NULL,
    CONSTRAINT FK_ESTADIAS_DEPOSITO FOREIGN KEY (ID_DEPOSITO)
        REFERENCES DEPOSITOS(ID_DEPOSITO),
    CONSTRAINT FK_ESTADIAS_CONTENEDOR FOREIGN KEY (ID_CONTENEDOR)
        REFERENCES CONTENEDORES(ID_CONTENEDOR),
    CONSTRAINT FK_ESTADIAS_TRASLADO FOREIGN KEY (ID_TRASLADO)
        REFERENCES TRASLADOS(ID_TRASLADO)
);

-- ========================================
-- TABLAS DE HISTÓRICOS
-- ========================================

-- Tabla: HISTORICOS_ESTADOS_TRASLADOS
CREATE TABLE HISTORICOS_ESTADOS_TRASLADOS (
    ID_HISTORICO INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_HORA_INICIO_ESTADO TIMESTAMP,
    FECHA_HORA_FIN_ESTADO TIMESTAMP,
    ID_TRASLADO INT NOT NULL,
    ID_ESTADO_TRASLADO INT NOT NULL,
    CONSTRAINT FK_HISTORICOS_TRASLADO FOREIGN KEY (ID_TRASLADO)
        REFERENCES TRASLADOS(ID_TRASLADO),
    CONSTRAINT FK_HISTORICOS_ESTADO FOREIGN KEY (ID_ESTADO_TRASLADO)
        REFERENCES ESTADOS_TRASLADOS(ID_ESTADO_TRASLADO)
);

-- ========================================
-- ÍNDICES PARA MEJORAR RENDIMIENTO
-- ========================================

-- Índices en Foreign Keys principales
CREATE INDEX IX_CIUDADES_PROVINCIA ON CIUDADES(ID_PROVINCIA);
CREATE INDEX IX_CLIENTES_CIUDAD ON CLIENTES(ID_CIUDAD);
CREATE INDEX IX_TRANSPORTISTAS_CIUDAD ON TRANSPORTISTAS(ID_CIUDAD);
CREATE INDEX IX_CAMIONES_TARIFA ON CAMIONES(ID_TARIFA);
CREATE INDEX IX_DEPOSITOS_CIUDAD ON DEPOSITOS(ID_CIUDAD);
CREATE INDEX IX_CONTENEDORES_ESTADO ON CONTENEDORES(ID_ESTADO_CONTENEDOR);
CREATE INDEX IX_TRASLADOS_CIUDAD_ORIGEN ON TRASLADOS(ID_CIUDAD_ORIGEN);
CREATE INDEX IX_TRASLADOS_CIUDAD_DESTINO ON TRASLADOS(ID_CIUDAD_DESTINO);
CREATE INDEX IX_TRASLADOS_CONTENEDOR ON TRASLADOS(ID_CONTENEDOR);
CREATE INDEX IX_TRASLADOS_CLIENTE ON TRASLADOS(NRO_DOCUMENTO_CLIENTE);
CREATE INDEX IX_TRAMOS_ESTADO ON TRAMOS(ID_ESTADO_TRAMO);
CREATE INDEX IX_TRAMOS_TIPO ON TRAMOS(ID_TIPO_TRAMO);
CREATE INDEX IX_TRAMOS_CAMION ON TRAMOS(PATENTE_CAMION);
CREATE INDEX IX_TRAMOS_TRANSPORTISTA ON TRAMOS(LEGAJO_TRANSPORTISTA);
CREATE INDEX IX_TRAMOS_TRASLADO ON TRAMOS(ID_TRASLADO);
CREATE INDEX IX_ESTADIAS_DEPOSITO ON ESTADIAS(ID_DEPOSITO);
CREATE INDEX IX_ESTADIAS_CONTENEDOR ON ESTADIAS(ID_CONTENEDOR);
CREATE INDEX IX_ESTADIAS_TRASLADO ON ESTADIAS(ID_TRASLADO);
CREATE INDEX IX_HISTORICOS_TRASLADO ON HISTORICOS_ESTADOS_TRASLADOS(ID_TRASLADO);
CREATE INDEX IX_HISTORICOS_ESTADO ON HISTORICOS_ESTADOS_TRASLADOS(ID_ESTADO_TRASLADO);

-- Índices en campos de búsqueda frecuente
CREATE INDEX IX_CLIENTES_NOMBRE ON CLIENTES(NOMBRE, APELLIDO);
CREATE INDEX IX_TRANSPORTISTAS_NOMBRE ON TRANSPORTISTAS(NOMBRE, APELLIDO);
CREATE INDEX IX_CAMIONES_DISPONIBLE ON CAMIONES(ESTA_DISPONIBLE);
CREATE INDEX IX_TRASLADOS_FECHAS ON TRASLADOS(FECHA_INICIO_TRASLADO, FECHA_FIN_TRASLADO);
CREATE INDEX IX_TRAMOS_FECHAS ON TRAMOS(FECHA_HORA_INICIO_REAL, FECHA_HORA_FIN_REAL);
