# ========================================
# CONFIGURACION DEL SERVIDOR Y EXTERNOS
# ========================================
server.port={puerto_microservicio_propio}
# api.ms-camiones.base_url={puerto_microservicio}
api.ms-contenedores.base_url={puerto_microservicio}
api.ms-rutas.base_url={puerto_microservicio}
api.ms_traslados.base_url={puerto_microservicio}


# ========================================
# BASE DE DATOS H2 (en memoria)
# ========================================
spring.datasource.url=jdbc:h2:mem:{nombre_base};DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username={usuario}
spring.datasource.password=

# Consola web de H2 para ver/editar datos
# Acceso: http://localhost:{puerto_microservicio_propio}/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# ========================================
# JPA / HIBERNATE
# ========================================
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false


# ========================================
# LOGGING
# ========================================
logging.level.root=INFO
logging.level.com.backend_tpi.ms_traslados=DEBUG
# logging.level.org.springframework=WARN
logging.level.org.springframework.web=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# logging.level.org.hibernate.orm.jdbc.bind=TRACE

# logging.file.name=logs/ms-traslados.log
# logging.file.max-size=5MB
# logging.file.max-history=7

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level - %msg - %logger%n
# logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n


# ========================================
# JSON / SERIALIZACION
# ========================================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Argentina/Buenos_Aires


# ========================================
# VALIDACION
# ========================================
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
